export const COLLEGES = [
  "PSG College of Technology, Coimbatore",
  "PSG College of Arts and Science, Coimbatore",
  "Coimbatore Institute of Technology (CIT), Coimbatore",
  "Government College of Technology (GCT), Coimbatore",
  "Kumaraguru College of Technology (KCT), Coimbatore",
  "Sri Krishna College of Engineering and Technology (SKCET), Coimbatore",
  "Sri Ramakrishna Engineering College (SREC), Coimbatore",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "Kongu Engineering College, Erode",
  "Anna University, Chennai",
  "Madras Institute of Technology (MIT), Chennai",
  "SSN College of Engineering, Chennai",
  "SRM Institute of Science and Technology, Chennai",
  "Vellore Institute of Technology (VIT), Vellore",
  "National Institute of Technology (NIT), Tiruchirappalli",
  "Thiagarajar College of Engineering (TCE), Madurai",
  "Amrita Vishwa Vidyapeetham, Coimbatore",
  "Karunya Institute of Technology and Sciences, Coimbatore",
  "Hindusthan College of Engineering and Technology, Coimbatore",
  "Dr. Mahalingam College of Engineering and Technology (MCET), Pollachi",
  "RVS College of Engineering and Technology, Coimbatore",
  "SNS College of Technology, Coimbatore",
  "KPR Institute of Engineering and Technology, Coimbatore",
  "Other"
];
